name: PMD
on:
  push:
    branches:
      - "**" # Runs on push to any branch
  pull_request:
jobs:
  sonarcloud:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          version: '7.10.0'
          sourcePath: 'src/main/java'
          rulesets: 'pmd/ruleset.xml'

